/**
 * YSTI 题库与角色档案
 * 题目改编自常见性格底色量表（四维度 × 各五题），选项映射 E/I、S/N、T/F、J/P
 */

const DIMENSIONS = ["EI", "SN", "TF", "JP"];

const QUESTIONS = [
  {
    text: "在一个陌生的社交场合，你通常会：",
    options: [
      { label: "主动找人攀谈，很快融入氛围", scores: { EI: 2 } },
      { label: "先观察一会儿，再选择性加入对话", scores: { EI: 1 } },
      { label: "只和熟悉的人说话，保持小圈子", scores: { EI: -1 } },
      { label: "宁愿独处或提前离开，感到消耗", scores: { EI: -2 } },
    ],
  },
  {
    text: "周末难得空闲，你更想：",
    options: [
      { label: "约朋友出门聚餐、逛街或旅行", scores: { EI: 2 } },
      { label: "参加兴趣小组或线下活动", scores: { EI: 1 } },
      { label: "在家做自己的事，偶尔回消息", scores: { EI: -1 } },
      { label: "完全独处，看书、游戏或发呆", scores: { EI: -2 } },
    ],
  },
  {
    text: "遇到问题时，你倾向于：",
    options: [
      { label: "立刻找人讨论，边说边理清思路", scores: { EI: 2 } },
      { label: "先聊几句，再自己静下来想", scores: { EI: 0 } },
      { label: "独自想清楚大概，再选择性请教", scores: { EI: -1 } },
      { label: "完全在内心推演，很少向外倾诉", scores: { EI: -2 } },
    ],
  },
  {
    text: "别人对你的第一印象更可能是：",
    options: [
      { label: "热情开朗，容易接近", scores: { EI: 2 } },
      { label: "友善有礼，但不算张扬", scores: { EI: 1 } },
      { label: "安静礼貌，有距离感", scores: { EI: -1 } },
      { label: "冷淡神秘，难以看透", scores: { EI: -2 } },
    ],
  },
  {
    text: "长时间社交之后，你通常：",
    options: [
      { label: "仍然精力充沛，还想继续", scores: { EI: 2 } },
      { label: "有点累但心情不错", scores: { EI: 1 } },
      { label: "需要独处一阵才能恢复", scores: { EI: -1 } },
      { label: "感到严重透支，必须立刻逃离", scores: { EI: -2 } },
    ],
  },
  {
    text: "学习或工作时，你更信任：",
    options: [
      { label: "亲身经历与可验证的事实", scores: { SN: 2 } },
      { label: "步骤清晰、能立刻上手的做法", scores: { SN: 1 } },
      { label: "理论与模型背后的规律", scores: { SN: -1 } },
      { label: "直觉、联想和未来的可能性", scores: { SN: -2 } },
    ],
  },
  {
    text: "别人向你描述一件事时，你更关注：",
    options: [
      { label: "具体发生了什么、细节如何", scores: { SN: 2 } },
      { label: "是否真实、有没有证据", scores: { SN: 1 } },
      { label: "背后的动机与含义", scores: { SN: -1 } },
      { label: "它可能引向怎样的未来", scores: { SN: -2 } },
    ],
  },
  {
    text: "你更欣赏的人是：",
    options: [
      { label: "脚踏实地、做事靠谱", scores: { SN: 2 } },
      { label: "经验丰富、见多识广", scores: { SN: 1 } },
      { label: "富有想象力、见解独到", scores: { SN: -1 } },
      { label: "理想主义、能看透本质", scores: { SN: -2 } },
    ],
  },
  {
    text: "面对新任务，你通常会：",
    options: [
      { label: "按已有经验一步步来", scores: { SN: 2 } },
      { label: "先弄清要求，再动手做", scores: { SN: 1 } },
      { label: "先构想整体框架再细化", scores: { SN: -1 } },
      { label: "跳跃式尝试，在摸索中创新", scores: { SN: -2 } },
    ],
  },
  {
    text: "你觉得自己更像：",
    options: [
      { label: "现实的观察者", scores: { SN: 2 } },
      { label: "务实的执行者", scores: { SN: 1 } },
      { label: "意义的追寻者", scores: { SN: -1 } },
      { label: "可能性的探索者", scores: { SN: -2 } },
    ],
  },
  {
    text: "朋友做错事伤害了你，你更可能：",
    options: [
      { label: "直接指出问题，讲清道理", scores: { TF: 2 } },
      { label: "冷静分析对错，再决定态度", scores: { TF: 1 } },
      { label: "先顾及对方感受，委婉表达", scores: { TF: -1 } },
      { label: "优先维护关系，不忍说重话", scores: { TF: -2 } },
    ],
  },
  {
    text: "团队做决策时，你认为最重要的是：",
    options: [
      { label: "公平与效率，谁对谁错要分明", scores: { TF: 2 } },
      { label: "逻辑自洽，经得起推敲", scores: { TF: 1 } },
      { label: "每个人的感受都被照顾到", scores: { TF: -1 } },
      { label: "和谐氛围，避免有人受伤", scores: { TF: -2 } },
    ],
  },
  {
    text: "被人批评时，你内心第一反应是：",
    options: [
      { label: "对方说得对不对？哪里可以改", scores: { TF: 2 } },
      { label: "先剥离情绪，看事实", scores: { TF: 1 } },
      { label: "是不是我让人失望了", scores: { TF: -1 } },
      { label: "对方是不是不喜欢我了", scores: { TF: -2 } },
    ],
  },
  {
    text: "你更容易被怎样的人打动：",
    options: [
      { label: "原则坚定、头脑清晰", scores: { TF: 2 } },
      { label: "能力出众、值得信赖", scores: { TF: 1 } },
      { label: "温柔体贴、善解人意", scores: { TF: -1 } },
      { label: "真诚善良、富有共情", scores: { TF: -2 } },
    ],
  },
  {
    text: "在争论中，你更看重：",
    options: [
      { label: "真理与逻辑，哪怕伤了和气", scores: { TF: 2 } },
      { label: "结论是否合理、能否执行", scores: { TF: 1 } },
      { label: "双方是否还能做朋友", scores: { TF: -1 } },
      { label: "气氛是否还能缓和下来", scores: { TF: -2 } },
    ],
  },
  {
    text: "面对即将到期的任务，你通常：",
    options: [
      { label: "提前规划，按日程完成", scores: { JP: 2 } },
      { label: "列出清单，逐项勾选", scores: { JP: 1 } },
      { label: "先放着，压力来了再冲刺", scores: { JP: -1 } },
      { label: "随性发挥，截止前爆发", scores: { JP: -2 } },
    ],
  },
  {
    text: "你的房间或桌面一般是：",
    options: [
      { label: "井井有条，东西都有固定位置", scores: { JP: 2 } },
      { label: "大体整齐，偶尔乱一下", scores: { JP: 1 } },
      { label: "乱中有序，自己知道在哪", scores: { JP: -1 } },
      { label: "比较随意，找到就行", scores: { JP: -2 } },
    ],
  },
  {
    text: "旅行时你更喜欢：",
    options: [
      { label: "行程表排好，景点提前预约", scores: { JP: 2 } },
      { label: "大方向确定，细节可以微调", scores: { JP: 1 } },
      { label: "只定目的地，路上随机探索", scores: { JP: -1 } },
      { label: "说走就走，完全看当时心情", scores: { JP: -2 } },
    ],
  },
  {
    text: "对于规则和约定，你的态度是：",
    options: [
      { label: "应当遵守，破坏会带来混乱", scores: { JP: 2 } },
      { label: "多数时候遵守，特殊情况可变通", scores: { JP: 0 } },
      { label: "规则是参考，灵活更重要", scores: { JP: -1 } },
      { label: "讨厌被束缚，喜欢保留选择", scores: { JP: -2 } },
    ],
  },
  {
    text: "你觉得自己的人生节奏更像：",
    options: [
      { label: "有清晰目标的直线", scores: { JP: 2 } },
      { label: "阶段分明的阶梯", scores: { JP: 1 } },
      { label: "不断分叉的小路", scores: { JP: -1 } },
      { label: "随风飘荡、充满即兴", scores: { JP: -2 } },
    ],
  },
];

/** 18 位高人气角色（参考近年使用率与人气榜） */
const CHARACTERS = [
  {
    id: "furina",
    name: "芙宁娜",
    mbti: "ENFP",
    element: "hydro",
    emoji: "🎭",
    decor: "furina",
    traits: ["戏感", "骄傲", "深情"],
    desc: "你是天生的舞台主宰：在人群里光芒四射，用玩笑与表演挡住脆弱，却把最真的情绪留给极少数人。你相信世界需要戏剧性，也相信正义与美的表演同样能改变人心。",
    flair: "一记脱帽礼，一场独角戏——你把人生演成殿堂，却在帷幕后，悄悄把眼泪演给自己看。",
    vector: { EI: 2, SN: -1, TF: -1, JP: -1 },
  },
  {
    id: "mavuika",
    name: "玛薇卡",
    mbti: "ENFJ",
    element: "pyro",
    emoji: "🔥",
    decor: "mavuika",
    traits: ["领袖", "炽烈", "担当"],
    desc: "你像火神一样站在队伍最前方：目标清晰、言语有感染力，愿意为信念点燃自己。你未必永远正确，但绝不会让同伴独自面对黑暗。",
    flair: "别人看见的是烈焰，你肩上扛的是整片夜空的重量——领袖的宿命，是把光分给大家，把伤留给自己。",
    vector: { EI: 2, SN: -1, TF: -1, JP: 2 },
  },
  {
    id: "hutao",
    name: "胡桃",
    mbti: "ESFP",
    element: "pyro",
    emoji: "👻",
    decor: "hutao",
    traits: ["跳脱", "通透", "戏谑"],
    desc: "你活得鲜明而当下：敢拿生死开玩笑，却比别人更懂生命的分量。热闹是你的铠甲，内里是对人间温柔的洞察——越荒诞的笑话，越接近真相。",
    flair: "「往生堂第七十七代堂主」式的自我介绍背后，是你把沉重讲成段子、把告别唱成诗的天赋。",
    vector: { EI: 2, SN: 2, TF: -1, JP: -2 },
  },
  {
    id: "sigewinne",
    name: "希格雯",
    mbti: "ESFJ",
    element: "hydro",
    emoji: "💉",
    decor: "sigewinne",
    traits: ["治愈", "细腻", "执拗"],
    desc: "你是那种会让人放松下来的存在：记得小细节、照顾到角落里的情绪，用温柔把团队缝补完整。你的善良有锋芒——对伤害他人的事，绝不妥协。",
    flair: "护士长的微笑是职业，也是选择：你把「让人好起来」当成终身课题，包括那些不肯承认自己受伤的人。",
    vector: { EI: 2, SN: 1, TF: -2, JP: 1 },
  },
  {
    id: "arlecchino",
    name: "阿蕾奇诺",
    mbti: "ESTP",
    element: "pyro",
    emoji: "🌙",
    decor: "arlecchino",
    traits: ["冷酷", "掌控", "母性"],
    desc: "你行事利落、讨厌废话，习惯用结果代替解释。外表如刃，内里却有明确的秩序与守护——你认定的「家人」，会用一切手段护到底。",
    flair: "壁炉之家的「父亲」从不是温情的代名词，而是你重新定义的契约：残酷训练，是为了让他们在真实世界里站着活下去。",
    vector: { EI: 1, SN: 2, TF: 1, JP: -1 },
  },
  {
    id: "neuvillette",
    name: "那维莱特",
    mbti: "ENTJ",
    element: "hydro",
    emoji: "🐉",
    decor: "neuvillette",
    traits: ["公正", "疏离", "悲悯"],
    desc: "你以理性与规则为尺，却并非没有温度——只是情绪被你翻译成「应当如何」。你看重公平胜过讨好，愿意为长远秩序承受当下的误解。",
    flair: "最高审判官的沉默里，藏着龙族对人类的观察：你学会用人的法律审判世界，也学会在暴雨里为无辜者落泪。",
    vector: { EI: -1, SN: -1, TF: 2, JP: 2 },
  },
  {
    id: "yae",
    name: "八重神子",
    mbti: "ENTP",
    element: "electro",
    emoji: "🦊",
    decor: "yae",
    traits: ["狡黠", "洞察", "从容"],
    desc: "你思维快、嘴也快，喜欢用玩笑试探人心。别人以为你在玩，其实你在读局——故事、权力与欲望，在你眼里都是可翻阅的书页。",
    flair: "轻小说主编也好，宫司大人也罢，你真正沉迷的是「下一章会怎样」——人生对你，是永远连载的乐子。",
    vector: { EI: 1, SN: -2, TF: 1, JP: -1 },
  },
  {
    id: "zhongli",
    name: "钟离",
    mbti: "INFJ",
    element: "geo",
    emoji: "🪨",
    decor: "zhongli",
    traits: ["沉稳", "契约", "远见"],
    desc: "你重诺、重义、重时间沉淀下来的重量。不爱抢话，却能在关键处一语定音。你像行走的史书，把往事折成建议，递给愿意听的人。",
    flair: "「这是契约，不可违背。」——你把承诺看得比输赢更重；世人见你从容，不知你曾为一座城、一种记忆，独自守过千年。",
    vector: { EI: -2, SN: -1, TF: 1, JP: 2 },
  },
  {
    id: "kazuha",
    name: "枫原万叶",
    mbti: "INFP",
    element: "anemo",
    emoji: "🍁",
    decor: "kazuha",
    traits: ["洒脱", "感怀", "侠义"],
    desc: "你内心柔软，却选择漂泊：把故乡与故人收进诗里，把刀留在该出鞘的一刻。自由对你不是任性，而是对「必须如此」的温柔抵抗。",
    flair: "「此身虽作客，此心随海风」——你把遗憾酿成俳句，把义字写在浪里，一路向南。",
    vector: { EI: -1, SN: -2, TF: -2, JP: -2 },
  },
  {
    id: "raiden",
    name: "雷电将军",
    mbti: "INTJ",
    element: "electro",
    emoji: "⚡",
    decor: "raiden",
    traits: ["永恒", "决断", "执着"],
    desc: "你目标宏大、原则分明，愿意为信念付出一切。你害怕失去，所以追求不变——却在漫长的静止里，慢慢学会「改变」也是慈悲。",
    flair: "一心净土外的尘世，对你曾是噪音；直到你发现，永恒若没有人间烟火，不过是冰冷的标本。",
    vector: { EI: -2, SN: -2, TF: 2, JP: 2 },
  },
  {
    id: "wanderer",
    name: "流浪者",
    mbti: "INTP",
    element: "anemo",
    emoji: "🎭",
    decor: "wanderer",
    traits: ["孤傲", "思辨", "破碎"],
    desc: "你用刺话和冷漠把世界推开半步，脑子却转得比谁都快。你厌恶被定义，又渴望被理解——像风，拒绝笼，却愿为一人停。",
    flair: "「我曾以为名分与神之心能填满空洞。」——你把答案从神座换成人间，虽然嘴上说不在乎，脚步却往光亮处挪。",
    vector: { EI: -2, SN: -1, TF: 2, JP: -2 },
  },
  {
    id: "nahida",
    name: "纳西妲",
    mbti: "ISFJ",
    element: "dendro",
    emoji: "🌿",
    decor: "nahida",
    traits: ["智慧", "慈悲", "守候"],
    desc: "你安静、细腻，愿意花时间听懂每一片叶子的语言。你不急着表态，却在长久观察后给出最温柔的解法——像草木，慢，却生生不息。",
    flair: "被囚禁在梦里五百年的神明，仍把「学习」当作礼物：你相信理解能化解仇恨，相信种子终会破土。",
    vector: { EI: -1, SN: -2, TF: -2, JP: 1 },
  },
  {
    id: "wriothesley",
    name: "莱欧斯利",
    mbti: "ISTJ",
    element: "cryo",
    emoji: "⛓️",
    decor: "wriothesley",
    traits: ["自律", "底线", "克制"],
    desc: "你在规则与灰色地带之间走钢丝：外表散漫，内里纪律严明。对自己狠，对越界的事更狠——正义对你不是口号，是日常管理的秩序。",
    flair: "梅洛彼得堡的公爵，拳击场的王者，也是自己过去的审判者：你把赎罪写在每一记直拳里。",
    vector: { EI: -1, SN: 2, TF: 2, JP: 2 },
  },
  {
    id: "nilou",
    name: "妮露",
    mbti: "ISFP",
    element: "dendro",
    emoji: "💃",
    decor: "nilou",
    traits: ["纯粹", "艺术", "柔韧"],
    desc: "你用身体与表情说话，把情绪化成舞步。不擅长争辩，却擅长让人看见美——你相信温柔与创造，能软化最硬的墙。",
    flair: "祖拜尔剧场的星光不是天赋 alone，是你把「让人微笑」当作比胜利更重要的谢幕。",
    vector: { EI: 0, SN: 1, TF: -2, JP: -2 },
  },
  {
    id: "yelan",
    name: "夜兰",
    mbti: "ISTP",
    element: "hydro",
    emoji: "🎲",
    decor: "yelan",
    traits: ["冷静", "算计", "随性"],
    desc: "你像棋手，也像赌徒：情报、时机与一点恶作剧，都是你的武器。表面慵懒，出手却精准——麻烦事留给你，反而最让人安心。",
    flair: "丝线缠指，骰子落定；你说「人生如戏」，却把真相藏在笑里，等敌人自己走进局。",
    vector: { EI: 0, SN: 2, TF: 1, JP: -2 },
  },
  {
    id: "lyney",
    name: "林尼",
    mbti: "ESTJ",
    element: "pyro",
    emoji: "🎩",
    decor: "lyney",
    traits: ["表演", "责任", "隐忍"],
    desc: "你把计划藏在笑容与礼帽后面，习惯替家人扛起观众看不见的部分。外向、得体、可靠——只有你知道，舞台灯光熄灭后有多累。",
    flair: "「欢迎来到魔术秀！」——幕布后是壁炉家的长兄，是把恐惧变成戏法、把守护变成日常的魔术师。",
    vector: { EI: 2, SN: 1, TF: 1, JP: 2 },
  },
  {
    id: "chasca",
    name: "恰斯卡",
    mbti: "ISTP",
    element: "anemo",
    emoji: "🦅",
    decor: "chasca",
    traits: ["孤高", "调解", "果决"],
    desc: "你习惯从高处看纷争，用一枪一线划开僵局。不爱热闹，却在矛盾最尖锐时出现——像风，冷冽，却能吹散毒雾。",
    flair: "调停者坐在枪炮与誓言之间：你信「和平」不是软弱，是另一种更难的瞄准。",
    vector: { EI: -2, SN: 2, TF: 1, JP: -1 },
  },
  {
    id: "kinich",
    name: "基尼奇",
    mbti: "INTP",
    element: "dendro",
    emoji: "🦎",
    decor: "kinich",
    traits: ["冷静", "契约", "毒舌"],
    desc: "你把世界换算成交易与条款，嘴硬心也硬——却会为契约另一端的人，默默把危险挡在外面。理性是你的甲，义气是内衬。",
    flair: "「成交。」——龙伙伴、悬赏金、规则书，构成你的语言；人情味？藏在不打折的价码后面。",
    vector: { EI: -2, SN: 1, TF: 2, JP: 1 },
  },
];

const CHARACTER_VISUALS = {
  furina: "elegant hydro archon-like lady, white blue opera dress, dramatic pose on stage",
  mavuika: "fiery warrior queen, long red hair, molten armor, sunset battlefield",
  hutao: "playful funeral director girl, black red chinese dress, ghost fire smile",
  sigewinne: "cute melusine nurse, pink blue outfit, bubbles and healing light",
  arlecchino: "elegant stern father figure, black white suit, crimson moon aura",
  neuvillette: "noble hydro dragon judge, white coat, rain and scales motif",
  yae: "pink fox shrine maiden, many tails illusion, sly smile",
  zhongli: "tall geo gentleman, brown suit, amber eyes, stone runes",
  kazuha: "wandering samurai poet, red scarf, autumn maple leaves",
  raiden: "purple braided electro shogun, katana, musou isshin glow",
  wanderer: "floating hat youth, dark blue outfit, sharp gaze wind",
  nahida: "small dendro sage girl, white green hair, lotus sanctuary",
  wriothesley: "boxer duke, cryo cuffs, dark coat, arena lights",
  nilou: "dancer in blue gold, lotus stage, graceful spin",
  yelan: "sleek spy lady, green dress, dice and water threads",
  lyney: "magician boy, top hat, cards and fire tricks smile",
  chasca: "sky hunter, anemo glider, desert canyon, rifle pose",
  kinich: "cool bounty hunter, saurian companion, jungle contract scroll",
};

CHARACTERS.forEach((c) => {
  c.visual = CHARACTER_VISUALS[c.id] || "fantasy traveler";
});
